openscanhub/openscanhub

.github/workflows/lint.yml

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/84

ci: Add lint workflow for GitHub Actions

---

.github/workflows/django-unit-tests.yml

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/84

ci: Run django unit tests through GitHub Actions

---

.github/workflows/integration-tests.yml

... on `push` and `pull_request` events.
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/265

ci: Run integration tests workflow on `main` branch

---

docs/development.md

docs: Remove references to internal GitLab repository

---

docs/development.md

docs: Remove reference to internal database dump

---

osh/hub/waiving/results_loader.py

Fix a minor logging issue in hub.

hub: fix a minor TypeError in logging.

---

osh.spec
osh/client/completion/_osh-cli
setup.py

client: add completions for ZSH 

---

osh/hub/stats/models.py
osh/hub/stats/service.py
osh/hub/stats/urls.py

See the messages of following commits.

hub: refactor and simplify the `stats` app - Part 1

---

.github/workflows/django-unit-tests.yml

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/264

ci: Upload unit tests coverage report to Codecov

---

codecov.yml

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/264

ci: Disable comments from Codecov

---

osh/hub/settings_local.ci.py
osh/hub/settings_local.py
osh/hub/waiving/reporting/bugzilla.py

Closes: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/276

hub: waiving/reporting: bugzilla: use base link on settings

---

osh/hub/scan/models.py

Please review on https://gitlab.cee.redhat.com/covscan/covscan/-/merge_requests/377 if possible.

hub: scan/models: small improvements for SystemRelease

---

.github/workflows/integration-tests.yml
containers/scripts/generate_integration_test_coverage.sh

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/264

ci: Upload integration tests coverage report to Codecov

---

containers/scripts/generate_integration_test_coverage.sh
osh/client/commands/cmd_diff_build.py
osh/client/commands/cmd_version_diff_build.py
osh/client/commands/shortcuts.py

client: do not crash on unknown profile

---

.github/workflows/django-unit-tests.yml
compose.yaml
containers/client.Dockerfile
containers/hub/Dockerfile
containers/hub/run.sh
containers/scripts/deploy.sh
containers/scripts/generate_integration_test_coverage.sh
containers/scripts/utils.sh
containers/worker.Dockerfile
osh/hub/settings_local.ci.py
osh/hub/settings_local.py

Depends on #67!
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/255

hub: fix task execution with rootless podman

---

.gitignore
docs/development.md
osh.spec
osh/hub/settings.py
osh/hub/settings_local.ci.py
osh/hub/settings_local.py

Closes: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/241

hub: improve secret handling

---

osh/hub/templates/waiving/result.html
osh/hub/waiving/service.py
osh/hub/waiving/views.py

hub: remove dead code from `waiving/service.py`

---

.github/workflows/django-unit-tests.yml
.github/workflows/integration-tests.yml
.github/workflows/lint.yml
containers/scripts/generate_integration_test_coverage.sh
containers/scripts/init-db.sh

Removes redundant steps and makes the configuration files easier to read.

ci: refactor GitHub Actions configuration

---

containers/scripts/generate_integration_test_coverage.sh
docs/development.md
osh/client/commands/cmd_diff_build.py
osh/client/commands/cmd_version_diff_build.py
osh/client/commands/common.py
osh/client/completion/_osh-cli
osh/client/completion/osh-cli.bash
scripts/cli_sanity_test.sh
tests/ci.sh

Marked as draft until the Testing Farm CI is green again.

client: rename `--{base-,}brew-build` options to `--{base-,}nvr`

---

osh.spec

Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/272

packaging: Follow Fedora packaging guidelines

---

README.md
osh.spec
osh/hub/osh_xmlrpc/client.py
osh/hub/osh_xmlrpc/worker.py
osh/hub/scan/xmlrpc_helper.py
osh/hub/settings.py
osh/worker/tasks/task_build.py
osh/worker/tasks/task_errata_diff_build.py
osh/worker/tasks/task_get_analyzer_versions.py

See commit messages for details.

worker + hub: make handling of ErrataDiffTasks more robust 

---

tests/ci.sh

This must be a Draft until the `mock` issue with EPEL is resolved.

ci: refactor Testing Farm tests

---

osh/hub/scan/service.py

This is a follow-up to #119 which I already had prepared locally.

hub: refactor `get_latest_binding`

---

.packit.yaml

Resolves: https://github.com/openscanhub/openscanhub/issues/138

ci: run Testing Farm tests on commits to main branch

---

osh.spec
setup.py

Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/256
Fixes: https://github.com/openscanhub/openscanhub/issues/165

packaging: stabilize a new version of osh-client

---

osh/hub/osh_xmlrpc/client.py
osh/hub/osh_xmlrpc/errata.py
osh/hub/osh_xmlrpc/mock_config.py
osh/hub/osh_xmlrpc/scan.py
osh/hub/osh_xmlrpc/worker.py

hub: do not export unwanted XML-RPC methods

---

containers/hub/run.sh
osh/hub/scan/fixtures/initial_data.json
osh/hub/waiving/fixtures/initial_data.json
scripts/setup_db.sh
setup.py

* enable smatch in fixtures
* update fixtures to only include publicly available products and mock configs

hub: update fixtures

---

README.md
osh.spec
osh/hub/menu.py

Resolves: https://github.com/openscanhub/openscanhub/issues/85
Related: https://github.com/release-engineering/kobo/pull/231
Related: https://issues.redhat.com/browse/OSH-340

hub: add menu item for failed tasks

---

osh/hub/scan/models.py
osh/hub/scan/service.py
osh/hub/templates/waiving/result.html
osh/hub/waiving/views.py

Resolves: https://github.com/openscanhub/openscanhub/issues/110

hub: fix waiver scan navigation

---

osh/client/commands/cmd_task_info.py
osh/client/completion/_osh-cli
osh/client/completion/osh-cli.bash

Resolves: https://issues.redhat.com/browse/OSH-371

client: implement JSON output for the task-info command

---

osh/client/commands/cmd_build.py
osh/client/commands/common.py
osh/client/completion/_osh-cli
osh/client/completion/osh-cli.bash

Resolves: https://issues.redhat.com/browse/OSH-371

client: add option to build commands for task details in JSON

---

osh/hub/scan/forms.py

... in the scan submission form.

hub: change default scan type to `mockbuild`

---

osh/hub/scan/notify.py

Resolves: https://issues.redhat.com/browse/OSH-200

hub: notify the admin about failed tasks

---

osh/client/commands/cmd_build.py
osh/client/commands/cmd_version_diff_build.py
osh/hub/scan/scanner.py

Resolves: https://issues.redhat.com/browse/OSH-147

client: add support for `VersionDiffBuild` tarball scanning

---

osh/worker/csmock_runner.py

Resolves: https://issues.redhat.com/browse/OSH-246

worker: capture the koji download progress

---

containers/hub/Dockerfile
containers/hub/run.sh
osh/hub/templates/waiving/list.html

* containers: use containers/hub/run.sh from the host
* containers: execute hub/run.sh with set -ex
* hub: make display of search boxes consistent

containers+hub: minor improvements

---

README.md
containers/hub/run.sh
osh.spec
osh/hub/scan/fixtures/initial_data.json
osh/hub/scan/scanner.py
osh/worker/tasks/task_build.py
osh/worker/tasks/task_errata_diff_build.py
osh/worker/tasks/task_get_analyzer_versions.py
scripts/add-worker-arch.py
tests/ci.sh

Resolves: https://github.com/openscanhub/openscanhub/issues/200
Blocked by: https://github.com/release-engineering/kobo/pull/237

hub: use native architectures by default

---

osh/client/commands/cmd_find_tasks.py
osh/client/completion/_osh-cli
osh/client/completion/osh-cli.bash
osh/hub/osh_xmlrpc/scan.py

Resolves: https://issues.redhat.com/browse/OSH-304
Closes: https://github.com/openscanhub/openscanhub/pull/224

client: ability to find tasks by comment

---

osh/client/commands/shortcuts.py

Related: https://issues.redhat.com/browse/OSH-144

client: catch network connectivity exceptions when verifying builds

---

osh/client/osh-cli

Related: https://issues.redhat.com/browse/OSH-144

client: capture other exceptions when cli runs

---

osh/hub/scan/notify.py
osh/hub/settings.py
osh/hub/settings_local.py

... to the user configurable.
Resolves: https://github.com/openscanhub/openscanhub/issues/253

hub: make domain name for sending notifications

---

osh.spec

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2275304

spec: tweak spec file based on Fedora review

---

README.md

... in the `README.md`.
Resolves: https://github.com/openscanhub/openscanhub/issues/154

docs: add reference to Fedora wiki page

---

osh/hub/waiving/results_loader.py

Resolves: https://github.com/openscanhub/openscanhub/issues/133

hub: embed results summary in `Task.result` field

---

.packit.yaml
osh.spec

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2275304

spec: more fixes based on Fedora review

---

containers/scripts/generate_integration_test_coverage.sh
osh/hub/osh_xmlrpc/worker.py
osh/hub/scan/fixtures/initial_data.json
osh/hub/scan/mock.py
osh/hub/scan/scanner.py
osh/hub/settings.py
osh/hub/settings_local.ci.py
osh/hub/settings_local.py
osh/worker/csmock_runner.py
osh/worker/tasks/task_build.py
osh/worker/tasks/task_errata_diff_build.py
tests/ci.sh

hub: implement dynamic generation of mock configs

---

README.md
osh.spec
osh/worker/osh-worker.service

Highlights:
* worker: add support for service reloading
* worker: set service `KillMode` to `mixed`

worker: `osh-worker.service` improvements

---

osh/hub/osh_xmlrpc/scan.py

Related: https://issues.redhat.com/browse/OSH-573

hub/client: order tasks by id in find-tasks

---

osh/hub/scan/check.py
osh/hub/scan/mock.py
osh/hub/scan/scanner.py

hub: add automatic mock config detection for container scans

---

osh/hub/scan/mock.py

Related: https://issues.redhat.com/browse/OSH-490

hub: fix generation of mock configs for module builds

---

osh/hub/scan/mock.py

hub: fix compatibility with Fedora ELN

---

osh.spec

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2275304

spec: some more fixes based on Fedora review

---

docs/scanning_releases.md
osh/hub/osh_xmlrpc/worker.py
osh/hub/scan/scanner.py
osh/hub/scripts/osh-xmlrpc-client.py

Resolves: https://issues.redhat.com/browse/OSH-69

hub: handle `rhel_version` option for ASYNC ET advisories

---

osh/hub/scan/mock.py

... for module koji builds.
Resolves: https://issues.redhat.com/browse/OSH-69

hub: fix conversion of external repos to build tags

---

osh/hub/scan/scanner.py

hub: fix `kpatch-patch` not being blocked with `auto` mock configs

---

containers/client.Dockerfile
containers/hub/Dockerfile
containers/worker.Dockerfile

Related: https://github.com/openscanhub/openscanhub/issues/263

containers: fix appstream mirror issue

---

osh/hub/static-assets/css/redhat.css

... to make it easier to read.

hub: make the footer slightly bigger

---

osh/hub/scan/service.py
osh/hub/service/processing.py

... instead of "defects" in the reports.
Resolves: https://github.com/openscanhub/openscanhub/issues/297

hub: use the term "findings"

---

osh/hub/scan/test_admin.py
osh/testing/html.py
osh/testing/testcases.py
osh/testing/testdata.py
setup.py

hub: add `ScanAdmin` interface tests

---

.github/workflows/django-unit-tests.yml
osh.spec
osh/client/tests/__init__.py
osh/client/tests/test_cmd_build.py
osh/client/tests/test_cmd_diff_build.py
osh/client/tests/test_cmd_download_results.py
osh/client/tests/test_cmd_find_tasks.py
osh/client/tests/test_cmd_list_analyzers.py
osh/client/tests/test_cmd_list_mock_configs.py
osh/client/tests/test_cmd_list_profiles.py
osh/client/tests/test_cmd_mock_build.py
osh/client/tests/test_cmd_task_info.py
osh/client/tests/test_cmd_version_diff_build.py

The modules can be tested via:
```
coverage run -m unittest discover -s osh/client/tests -v
```
Latest coverage report
```
Name                                            Stmts   Miss  Cover
-------------------------------------------------------------------
osh/__init__.py                                     0      0   100%
osh/client/__init__.py                             16      4    75%
osh/client/commands/__init__.py                     0      0   100%
osh/client/commands/cmd_build.py                  121      9    93%
osh/client/commands/cmd_diff_build.py              15      0   100%
osh/client/commands/cmd_download_results.py        29      1    97%
osh/client/commands/cmd_find_tasks.py              50      0   100%
osh/client/commands/cmd_list_analyzers.py          16      0 …
```

Add osh-cli unit test cases

---

osh/hub/osh_xmlrpc/worker.py

... and use only `started` and `finished` topics for each task.
Related: https://github.com/openscanhub/fedora-infra/issues/3

hub: update message topics for fedora

---

containers/client.Dockerfile
containers/hub/Dockerfile
containers/worker.Dockerfile
osh/client/client-local.conf
osh/client/client.conf
osh/hub/scan/check.py

Related: https://github.com/openscanhub/openscanhub/issues/127

Add support for CentOS Stream koji

---

osh/hub/scan/mock.py

the ubi10 image is now available

hub: remove f40 bootstrap image for RHEL-10
