openscanhub/openscanhub

.packit.yaml
Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/84
=> ci: Groups in packit are prefixed with `@`

.github/workflows/lint.yml
... and `push` events on the `main` branch.
Related: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/84
=> ci: lint workflow should execute on `pull_request`

docs/development.md
... as it may be confusing to new contributors and can be misinterpreted for `..` i.e. parent directory instead of current directory.
=> docs: Remove extra `.` in a sentence in development doc

.github/workflows/django-unit-tests.yml, .github/workflows/integration-tests.yml
An update in the podman package in latest Ubuntu has caused broken network functionality, which is causing failures in the CI.
These changes are a workaround for this bug and should be reverted when this bug has been fixed.
Related: https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
=> ci: Use older version of Ubuntu to run podman compose

osh.spec
... when installing the worker or hub packages.  We use systemd to write the worker log now and systemd does not automatically create the directory (unlike the osh-worker daemon).
Fixes: commit 30fadad7945a4c1de316956a77641b93a99bd649
=> packaging: create the /var/log/osh directory

osh/client/commands/cmd_diff_build.py, osh/client/commands/cmd_download_results.py, osh/client/commands/shortcuts.py
Since 1fce0c12ad4ab5fafef7a503c462b479f1d2cc60, all tasks submitted through the client have a `result_filename` argument that defines the filename without extensions of the tarball with scan results.  So we should use if it is available.  Otherwise, fall back on the previous implementation.
Related: 1fce0c12ad4ab5fafef7a503c462b479f1d2cc60 ("support scanning of tarballs")
=> client: fix downloading of results for non-RPM tasks

osh/client/commands/shortcuts.py, osh/hub/errata/check.py
Such builds do not contain any source RPM packages, e.g. https://koji.fedoraproject.org/koji/buildinfo?buildID=2097678.
=> client + hub: mark module metadata builds as not eligible for scanning 

osh/hub/scan/fixtures/initial_data.json
So that users can use the default configuration also on aarch64 machines.
Related: https://github.com/openscanhub/openscanhub/pull/29/files#r1255756164
=> hub: add a fixture for the `fedora-37-aarch64` mock config

.github/workflows/coverity.yml
At the moment, it is only possible to scan the `main` branch.  This PR is exceptionally done from the repository itself to test that all other Coverity related settings are configured correctly.
Resolves: https://github.com/openscanhub/openscanhub/issues/32
=> ci: enable scanning with Coverity

osh/hub/templates/waiving/result.html
This code has been commented out since it was introduced in 26d5d46. Moreover, the usage of Django's comment tags is not compatible with Coverity's JavaScript parser.
Fixes: 26d5d46a69a87e3188ce79af8b1ef9411a559dd0 ("UI revamp -- tabs addition, new group")
Resolves: https://github.com/openscanhub/openscanhub/issues/32
=> hub: remove dead JavaScript code

docs/development.md
I believe the bug was fixed a year ago:
https://bugzilla.redhat.com/2038126
Reported-by: Chuntao Han
Closes: https://github.com/openscanhub/openscanhub/pull/53
=> docs: drop outdated note about broken podman-compose

.github/workflows/differential-shellcheck.yml
Differential ShellCheck is a GitHub Action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.
Your scripts are in great shape, but I think you might find the `differential-shellcheck` Action useful. It is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to extend functionality.
=> Add shell linter - Differential ShellCheck

docs/development.md
... that we use in the development environment
Reported-by: Chuntao Han
Fixes: commit 72b5df2afab1e2cfac94db927797fa7d3fe203a3
Closes: https://github.com/openscanhub/openscanhub/pull/53
=> docs: reflect change of the postgresql image

codecov.yml
CI should not fail if a line changed through a patch is not covered by tests.
=> ci: Disable patch check in codecov

osh.spec
Django 3.2 is now finally available in EPEL-9:
https://bugzilla.redhat.com/2033064
Closes: https://gitlab.cee.redhat.com/covscan/covscan/-/merge_requests/363
=> packaging: build a working osh-hub for EPEL-9

.github/workflows/django-unit-tests.yml, compose.yaml, containers/scripts/deploy.sh, containers/scripts/generate_integration_test_coverage.sh, containers/scripts/init-db.sh, containers/scripts/utils.sh
See the commit messages for details.
Test cases:
* `containers/scripts/deploy.sh`
* `containers/scripts/deploy.sh --clean`
* `containers/scripts/init-db.sh --force --restore`
* `containers/scripts/init-db.sh --force --minimal`
Workers do not work properly in `podman` on macOS for now.  However, that was already the case for rootless `podman` containers on my Arch machine so I would not classify that as a regression.
edit: add `--minimal` test case
=> containers: add support for Docker on Linux and Podman on macOS

osh/client/completion/osh-cli.bash
... for the old client binary name.
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/195
=> client: remove compatibility BASH completions

docs/development.md
The development docs are too verbose for an average new user. Add a quick set up section to make it easier for new users to try it in their local environment.
=> docs: Add a quick setup section in development docs

osh/hub/templates/base.html, osh/hub/templates/footer.html
... to make it easy to override.
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/174
=> hub: Move footer to a separate template

osh/hub/scan/fixtures/initial_data.json
Resolves: https://github.com/openscanhub/openscanhub/issues/28
=> hub: disable UMB messaging for development instances

osh/hub/stats/urls.py, osh/hub/stats/views.py, osh/hub/waiving/views.py
Resolves: https://issues.redhat.com/browse/OSH-175
Do not forget to execute `osh-stats` and submit at least one ET task before testing!
Test cases (without changes traceback, after changes 404):
* http://0.0.0.0:8000/stats/123456789
* http://0.0.0.0:8000/stats/release/123456789
* http://0.0.0.0:8000/stats/release/54/123456789
* http://0.0.0.0:8000/stats/123456789/graph
* http://0.0.0.0:8000/stats/54/123456789/graph
* http://0.0.0.0:8000/waiving/?order_by=foo
* http://0.0.0.0:8000/waiving/1/123456789/fixed
`123456789` can be replaced by any other unknown ID.
edit: typo
=> hub: properly sanitize input urls

README.md, containers/client.Dockerfile, containers/hub/Dockerfile, containers/scripts/generate_integration_test_coverage.sh, containers/worker.Dockerfile, osh.spec
Minor improvements that should make the container builds a bit faster:
```console 
$ ./containers/scripts/deploy.sh --clean
$ time ./containers/scripts/deploy.sh --full-dev
...
66.46s user 35.73s system 36% cpu 4:37.33 total
$ ./containers/scripts/deploy.sh --clean
$ time ./containers/scripts/deploy.sh --full-dev
...
67.64s user 36.66s system 41% cpu 4:14.20 total
```
=> containers: speed-up container build

containers/hub/Dockerfile
... which was removed by mistake.
Fixes the following error:
```
/run.sh: line 9: pg_isready: command not found
/run.sh: line 9: pg_isready: command not found
/run.sh: line 9: pg_isready: command not found
...
```
Fortunately, the error is not fatal and the container would still start eventually.
Fixes: e309e3e0f674a9bca127128a1f8ebea3a28bae8d ("containers: do not install redundant packages")
=> containers: add `/usr/bin/pg_isready` to hub container

containers/scripts/deploy.sh
`prepare_deploy` function should not clean images from previous builds. Users should explicitly specify `--clean` option if they want to clear image cache from previous builds.
=> containers: Cleaning container images should be optional

osh/hub/static-assets/css/redhat.css, osh/hub/templates/scan/package_list.html
Kobo's CSS declare the `.paginator` class as `float`.  Therefore, in some cases the pagination controls would overlap with other page content making the visuals look corrupted.
Override the broken style in OSH because changes in kobo's styles may break other projects that depend on them.
Resolves: https://gitlab.cee.redhat.com/osh/covscan/-/issues/227
Testing instructions:
* Create a local OSH instance with the database snapshot restored.
* Check that all views with pagination controls are no longer corrupted with this PR appleid.
=> hub: fix overlapping pagination controls

osh/client/commands/cmd_diff_build.py, osh/client/commands/cmd_download_results.py, osh/client/commands/shortcuts.py
Fixes the following Traceback for tasks without any results:
```python
$ osh/client/osh-cli download-results 1
Downloading dotnet3.1-3.1.424-1.fc35.tar.xz
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/osh-cli", line 79, in <module>
main()
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/osh-cli", line 72, in main
parser.run()
File "/Users/lzaoral/redhat/OpenScanHub/kobo/kobo/cli.py", line 296, in run
cmd.run(*cmd_args, **cmd_kwargs)
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/commands/cmd_download_results.py", line 51, in run
fetch_results(self.hub, results_dir, task_id)
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/commands/shortcuts.py", line 138, in fetch_results
urlretrieve(url, local_path)
File …
```
=> client: add failure handling to `fetch_results`

osh/worker/csmock_runner.py
cspodman recently introduced the `-t` option compatible with csmock. So we can propagate the list of enabled analyzers for both the tools.
Related: https://issues.redhat.com/browse/OSH-313
=> worker: use the `-t` option for cspodman, too

osh/hub/templates/scan/new.html
This should make the scan submission form look a bit more professional and finished.
=> hub: use default styles for the scan submission form

codecov.yml
This should avoid any CI failures due to temporary low or inconsistent test coverage.
Resolves: https://github.com/openscanhub/openscanhub/issues/136
=> ci: set a minimal target for test coverage

osh/worker/tasks/task_errata_diff_build.py
... so that it is still created even when the parent task is killed by an exception.
Related: https://github.com/openscanhub/openscanhub/issues/156
=> worker: create a subtask `ScanBinding` before task assignment

osh/hub/settings.py
Related: https://github.com/release-engineering/kobo/pull/228
Related: https://github.com/release-engineering/kobo/issues/209
Related: https://issues.redhat.com/browse/OSH-78
This PR depends on upstream pull: https://github.com/release-engineering/kobo/pull/228
=> hub: restrict user list/detail page access to staff users only

osh/client/commands/shortcuts.py, osh/worker/csmock_runner.py
Fixes the following traceback:
```python
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/osh-cli", line 79, in <module>
main()
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/osh-cli", line 72, in main
parser.run()
File "/Users/lzaoral/redhat/OpenScanHub/kobo/kobo/cli.py", line 296, in run
cmd.run(*cmd_args, **cmd_kwargs)
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/commands/cmd_download_results.py", line 51, in run
fetch_results(self.hub, results_dir, task_id)
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/commands/shortcuts.py", line 128, in fetch_results
tarball = _get_result_filename(task_info['args']) + '.tar.xz'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/lzaoral/redhat/OpenScanHub/osh/client/commands/shortcuts.py", line …
```
=> client: fix downloading of AnalyzerVersionRetriever task results

osh/hub/waiving/service.py
If a `Sum` in a Django query is empty, the final value will be `None` and not `0` as one would expect.  Because the code returns `0` in case of the `KeyError` exception (which, by the way, cannot happen here...), it is safe to assume that the code is meant to return `0` in the case of no newly introduced defects.
When I was at it, I have also refactored the code a bit.
Fixes the following traceback:
```python
File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```
=> hub: return 0 if the sum in `get_scans_new_defects_count` is empty

osh/worker/osh-worker.service
As reported by Lukáš Zaoral, the default installation of OSH worker was writing each log message twice by mistake.  The log `LOG_FILE` field in the `worker.conf` configuration file works as expected in the foreground mode, too.  I must have done something wrong while testing it initially.
Fixes: commit 30fadad7945a4c1de316956a77641b93a99bd649
Closes: https://github.com/openscanhub/openscanhub/pull/173
=> worker: do not write to the log twice

README.md, osh.spec, osh/worker/tasks/task_build.py, osh/worker/tasks/task_errata_diff_build.py
... to fix the following crash due to race between the automated task assignment to workers by the hub and the `hub.worker.assign_task` XML-RPC method.
```python
File "/usr/lib/python3.9/site-packages/kobo/worker/taskmanager.py", line 423, in run_task
task.run()
File "/usr/lib/python3.9/site-packages/osh/worker/tasks/task_errata_diff_build.py", line 52, in run
self.hub.worker.assign_task(subtask_id)
File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
return self.__send(self.__name, args)
File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
response = self.__transport.request(
File "/usr/lib/python3.9/site-packages/kobo/xmlrpc.py", line 598, in request
result = transport_class.request(self, *args, **kwargs)
File …
```
=> worker: always create subtasks on the same worker

.github/workflows/coverity.yml
Fixes: 60a72f4145769ed066e58dd6f9b312b2a47f72a4 ("ci: scan the whole repository through Coverity")
=> ci: do not scan Coverity by Coverity

osh.spec
As we are in the process of containerizing hub and worker for production deployments, avoid having a hard dependency on osh configuration packages. The files provided by the configuration packages should be provided after the container build phase.
=> spec: change osh configuration packages to weak dependencies

containers/scripts/init-db.sh, docs/development.md, osh/hub/other/test_fixtures/README.md, osh/hub/other/test_fixtures/users.json
Note the similar user creation hack is also in `setup_db.sh`, with slight different password setup. Since it's used in ci, I didn't update there in this PR.
=> containers: get rid of user creation through shell

osh/client/commands/cmd_find_tasks.py, osh/client/completion/_osh-cli, osh/client/completion/main.py, osh/client/completion/osh-cli.bash, osh/hub/osh_xmlrpc/scan.py
This PR adds ability in `osh-client find-tasks` to filter tasks by state, used in conjunction with other options. Example:
```
$ osh-cli find-tasks --help
Usage: osh-cli find-tasks [options] <query_string>
Options:
-h, --help                  show this help message and exit
--username=USERNAME         specify user
--password=PASSWORD         specify password
--hub=HUB                   specify URL of XML-RPC interface on hub
-l, --latest                display only latest task
-r, --regex                 query by regular expression (python, module: re)
-p, --package               query by package name
-n, --nvr                   query by NVR (default one)
-s STATES, --states=STATES  query by task state. This option is used in
conjunction with -r, -p, or -n. Specify multiple
states by …
```
=> client: add --state option in `osh-cli find-tasks`

osh/hub/errata/scanner.py, osh/hub/osh_xmlrpc/worker.py
Fixes: 460aeea953a1918e55ad2ce4891c573be322297e ("hub: make ErrataDiffBuild task independent of ScanningSession")
Related: https://github.com/openscanhub/openscanhub/pull/170
Related: https://github.com/openscanhub/openscanhub/pull/191
=> hub: remove all remaining mentions to `ScanningSession`

osh.spec
Although the package is named `osh-client`, users know it as `osh-cli` because of how the executable is named.  This makes it easier for them to install it.
=> packaging: add a virtual provide for `osh-cli`

osh.spec
osh-worker does not implement `reload` and `restart` would interrupt running tasks.  Until a proper `reload` operation is implemented in the osh-worker daemon, it is better to let administrator restart it manually when they are ready for that (e.g. after setting `max_load` to zero and waiting for the already running tasks to finish).
Resolves: https://issues.redhat.com/browse/OSH-221
=> packaging: do not restart osh-worker upon update

osh.spec
For some reason, intransitive dependency on `/usr/bin/pg_isready` will install the `postgresql16` package which then conflicts with the `postgresql-server` installed by the Testing Farm.
This is a workaround for the following error:
```
+ dnf install -y openssl postgresql-server /usr/sbin/semanage
Last metadata expiration check: 0:00:07 ago on Mon 18 Dec 2023 08:20:03 AM UTC.
Package openssl-1:3.1.1-4.fc39.x86_64 is already installed.
Error:
Problem: problem with installed package postgresql16-16.1-1.fc39.x86_64
- package postgresql16-16.1-1.fc39.x86_64 from @System conflicts with postgresql provided by postgresql-15.4-1.fc39.i686 from fedora
- package postgresql16-16.1-1.fc39.x86_64 from testing-farm-tag-repository conflicts with postgresql provided by postgresql-15.4-1.fc39.i686 from …
```
=> packaging: install the suitable `postgresql` package directly

osh.spec, setup.py
This release includes the following user-visible changes:
- add support for tarballs scanning in `VersionDiffBuild` (#209)
- add support for search by comment in `osh-cli find-tasks` (#224)
Closes: https://github.com/openscanhub/openscanhub/pull/233
=> packaging: release osh-client-0.9.7

containers/hub/run.sh
This fixes a `osh-hub` container crash when starting with the database snapshot restored.
```
+ python3 scripts/add-worker-arch.py
File "scripts/add-worker-arch.py", line 28, in <module>
main()
File "scripts/add-worker-arch.py", line 19, in main
worker = Worker.objects.get(name='localhost')
File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 437, in get
self.model._meta.object_name
kobo.hub.models.DoesNotExist: Worker matching query does not exist.
```
=> containers: only set the worker container arch if the fixtures were loaded

osh/client/__init__.py
Previously, the code in OSH was not properly detecting the required support in `kobo`.
Fixes: 6d3e3cb3d57b0f4ca442ab919d2b6ee097032041 ("client: handle the --hub option globally")
=> client: fix the `--hub` option

osh.spec, osh/hub/osh-retention.service, osh/hub/osh-stats.service
They will be triggered by the systemd timer according to the configured schedule.
Also do not restart `osh-{retention,stats}.service` on failure.  These are one-shot services.  If something fails, which should not happen under normal circumstances, they will be started again by the systemd timer later on (daily in the default configuration).
Fixes: https://github.com/openscanhub/openscanhub/issues/235
=> packaging: do not trigger `osh-{retention,stats}.service` on each update of the RPM packages

osh/client/commands/cmd_find_tasks.py, osh/hub/osh_xmlrpc/scan.py
hub/client: truncate query results if `--latest` is specified in `find-task`
Resolves: https://issues.redhat.com/browse/OSH-573
Closes: https://github.com/openscanhub/openscanhub/pull/236
=> hub/client: truncate results if `--latest` is specified in `find-task`

osh.spec, osh/client/client.conf, setup.py
Related: https://github.com/openscanhub/openscanhub/issues/195
=> client: change default hub url to Fedora deployment

osh/hub/settings.py
`DEFAULT_EMAIL_DOMAIN` should not contain the leading `@` because the concatenated string then contains `user@@redhat.com`, which results in difficult-to-debug failures to send e-mail notifications:
```
Apr 22 00:02:52 cov01.lab.eng.brq2.redhat.com postfix/smtpd[2713480]: connect from localhost[::1]
Apr 22 00:02:53 cov01.lab.eng.brq2.redhat.com postfix/smtpd[2713480]: lost connection after CONNECT from localhost[::1]
Apr 22 00:02:53 cov01.lab.eng.brq2.redhat.com postfix/smtpd[2713480]: disconnect from localhost[::1] commands=0/0
Apr 22 00:05:08 cov01.lab.eng.brq2.redhat.com postfix/smtpd[2714548]: connect from localhost[::1]
Apr 22 00:05:08 cov01.lab.eng.brq2.redhat.com postfix/smtpd[2714548]: lost connection after CONNECT from localhost[::1]
Apr 22 00:05:08 cov01.lab.eng.brq2.redhat.com …
```
=> hub: fix a copy-paste error in the default e-mail domain

osh/hub/scan/notify.py, osh/hub/settings.py, osh/hub/settings_local.py
... configurable through settings.
Resolves: https://issues.redhat.com/browse/OSH-252
=> hub: make footer of the e-mail notifications

osh/hub/settings.py
=> hub: remove an unnecessary `os.path.join()` call

osh/hub/scan/notify.py
Resolves: https://github.com/openscanhub/openscanhub/issues/255
=> hub: remove `Hostname` field from task notifications

osh/hub/scan/mock.py
Related: https://issues.redhat.com/browse/OSH-538
=> hub: fix generation of mock configs for `wrapperRPM` tasks

osh/hub/scan/mock.py
... when applicable
Related: https://issues.redhat.com/browse/OSH-560
=> hub: explicitly enable bootstrap images with generated mock configs

osh/worker/csmock_runner.py
It was a potentially harmful interim solution, which is no longer needed.
The option is now ignored by cspodman anyway:
```
% cspodman --force-global-cleanup-on-exit ... 
cspodman: warning: --force-global-cleanup-on-exit is not implemented
[...]
``` 
Related: https://issues.redhat.com/browse/OSH-473
=> worker: do not use `cspodman --force-global-cleanup-on-exit`

osh/hub/scan/mock.py
... to avoid the following failure while scanning `less-530-1.el8` with `--config=auto`:
```
Dependencies resolved.
================================================================================
Package    Arch   Version                              Repository         Size
================================================================================
Installing:
ShellCheck x86_64 0.8.0-3.el8                          osh-shellcheck-epel
3.1 M
clang      x86_64 7.0.1-1.module+el8.0.0+3181+ec021930 build             722 k
xml-common noarch 0.6.3-50.el8                         build              38 k
Installing dependencies:
clang-libs x86_64 7.0.1-1.module+el8.0.0+3181+ec021930 build              16 M
libatomic  x86_64 8.2.1-3.5.el8                        build              19 k …
```
=> hub: use `module_hotfixes=True` for RHEL-8 and RHEL-9

README.md, containers/hub/Dockerfile, osh.spec, tests/ci.fmf
... to make OSH compatible with versioned Django packages in EPEL and Fedora.
=> packaging: use `python3dist` to specify django dependency

osh/client/commands/cmd_build.py, osh/client/commands/common.py, osh/client/completion/_osh-cli, osh/client/completion/osh-cli.bash, osh/hub/scan/check.py, osh/hub/scan/scanner.py
Related: https://issues.redhat.com/browse/OSH-567
Closes: https://github.com/openscanhub/openscanhub/pull/285
=> allow user to specify task metadata from client

osh/hub/scan/mock.py
Fixes: 8bb2b03 ("hub: fix generation of mock configs for noarch builds)
Related: https://issues.redhat.com/browse/OSH-538
=> hub: fix arch detection of mock configs for `wrapperRPM` tasks

.github/CODEOWNERS
The RHEL-related responsibilities take the majority of my work-time and I don't have time nor the motivation to be the main reviewer for this project.
From now on, I'd like to officially limit my contributions only to critical regressions which is the actual state of things for few past months anyway.  I'll try to finish #243 soon but other QOL improvements or (much needed) refactoring is out of scope for me.
=> codeowners: remove @lzaoral

osh/client/commands/common.py
otherwise the callback function is unable to correctly handle the value passed to the option, raising errors like this:
osh-cli: error: --metadata option does not take a value
Related: https://issues.redhat.com/browse/OSH-567
=> client: explicitly specify expected --metadata type

osh/client/commands/cmd_build.py, osh/client/commands/cmd_diff_build.py, osh/client/commands/cmd_mock_build.py, osh/client/commands/common.py, osh/client/completion/_osh-cli, osh/client/completion/osh-cli.bash, osh/common/validators.py, osh/hub/scan/scanner.py, osh/worker/csmock_runner.py, osh/worker/tasks/task_build.py
Resolves: https://issues.redhat.com/browse/OSH-592
=> mock-build to support --git-url option for scratch build

osh.spec, osh/hub/osh-hub-httpd.conf.in
psycopg2 does not work well on Fedora 41:
```
[Tue Nov 19 12:34:11.390423 2024] [wsgi:error] [pid 5254:tid 5355] [remote ::1:34968] mod_wsgi (pid=5254): Failed to exec Python script file '/usr/lib/python3.13/site-packages/osh/hub/osh-hub.wsgi'.
[Tue Nov 19 12:34:11.390462 2024] [wsgi:error] [pid 5254:tid 5355] [remote ::1:34968] mod_wsgi (pid=5254): Exception occurred processing WSGI script '/usr/lib/python3.13/site-packages/osh/hub/osh-hub.wsgi'.
[Tue Nov 19 12:34:11.397438 2024] [wsgi:error] [pid 5254:tid 5355] [remote ::1:34968] Traceback (most recent call last):
[Tue Nov 19 12:34:11.397635 2024] [wsgi:error] [pid 5254:tid 5355] [remote ::1:34968]   File "/usr/lib/python3.13/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
[Tue Nov 19 12:34:11.397643 2024] …
```
=> packaging: use psycopg3 on Fedora 41+

osh/hub/settings.py
... even when `?format=raw` is not used
Depends-on: https://github.com/release-engineering/kobo/pull/266
Fixes: https://github.com/openscanhub/openscanhub/issues/303
Closes: https://github.com/openscanhub/openscanhub/pull/306
=> hub: view JSON files unrendered

containers/scripts/generate_integration_test_coverage.sh
```
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:100:17: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:103:21: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:119:17: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:122:21: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:131:10: warning[SC2046]: Quote this to prevent word splitting. …
```
=> containers/scripts: fix issues reported by ShellCheck

osh/hub/waiving/views.py
This message was somewhat misleading, as it wasn't guaranteed that anyone was actually investigating the failed scan.
=> Remove "We are checking" from scan failed message

osh.spec, setup.py
... because the old macros will likely stop working in Fedora 45
Resolves: https://bugzilla.redhat.com/2377365
=> packaging: use newer RPM macros for build/install on f42+

.github/workflows/coverity.yml
Also extend the trigger for this workflow to a branch named `coverity` so that we can esily test changes in the CI configuration by pushing updates to the upstream `coverity` branch.
Related: https://github.com/csutils/csmock/issues/207
=> CI: make the `coverity` workflow work with up2date Coverity

osh/hub/scan/mock.py
When requesting a scan with --config=auto, a valid build target for the koji NVR is needed. If this was undefined it was possible koji.getTag() to be called with a null parameter, causing a stack trace. Instead let's raise a RuntimeError before calling getTag().
=> hub: improve error msg when generating mock config
